// THE RIGGED AVATAR (owner mandate 2026-08-22: full revamp, "even
// avatars"). One skinned figure replaces the three hand-built models
// (walker / skater / rider) so the player is ONE person by construction —
// the same argument wardrobe.js won for colors, now won for the body.
//
// Determinism: clips are sampled by a phase the GAME advances (distance /
// state time), never wall clock. Everything is data from
// src/avatar_data.js (baked by research/qlifegen/glbavatar.py — the
// qtrees/qlife pattern, no runtime GLB loader, no async boot path).
//
// Colors come from src/wardrobe.js via per-vertex GROUP indices; there is
// still nowhere else to put a clothing color. Vertex colors are LINEAR
// (the stage-1 washed-pastel lesson).
import * as THREE from '../lib/three.module.js';
import { AVATAR } from './avatar_data.js';
import { WARDROBE } from './wardrobe.js';

const lin = (hex) => [((hex >> 16 & 255) / 255) ** 2.2,
                      ((hex >> 8 & 255) / 255) ** 2.2,
                      ((hex & 255) / 255) ** 2.2];

// THE SOLVED SKATE STANCE, as a table in the solver's own knob order.
// Generated by scratchpad/stance.mjs against scratchpad/rig.mjs (a headless
// three.js copy of this rig) — see the long note at skatePose(). STAND is the
// cruising pose; DELTA is what full crouch adds. Every row is a local-axis
// rotation; the pelvis height is separate (SKATE_HIP) and imposed.
const SKATE_KNOBS = [
  ['Body', 0, 1, 0],
  ['UpperLeg.L', 1, 0, 0], ['UpperLeg.L', 0, 0, 1], ['LowerLeg.L', 1, 0, 0],
  ['UpperLeg.R', 1, 0, 0], ['UpperLeg.R', 0, 0, 1], ['LowerLeg.R', 1, 0, 0],
  ['Torso', 0, 1, 0], ['Torso', 1, 0, 0], ['Torso', 0, 0, 1],
  ['Head', 0, 1, 0], ['Head', 1, 0, 0],
  ['UpperArm.L', 1, 0, 0], ['UpperArm.L', 0, 0, 1], ['UpperArm.L', 0, 1, 0],
  ['LowerArm.L', 1, 0, 0], ['LowerArm.L', 0, 0, 1],
  ['UpperArm.R', 1, 0, 0], ['UpperArm.R', 0, 0, 1], ['UpperArm.R', 0, 1, 0],
  ['LowerArm.R', 1, 0, 0], ['LowerArm.R', 0, 0, 1],
];
// RE-SOLVED FROM REFERENCE 2026-08-26, after the first attempt was invented
// the same way the skate arms were. animationmentor's jump-and-land tutorial
// and endlessreference's jump breakdown both say it plainly: on the take-off
// the arms LEAD, driving up and forward to generate the momentum; on the
// landing they TRAIL the body — down and behind — while the knees absorb.
// The version this replaces threw them straight OVERHEAD at the apex (a
// cheer, which is exactly what the old clip-driven jump was criticised for)
// and straight out IN FRONT on the landing, which is leading, not trailing,
// and both with locked elbows. Elbows now read 78 deg at the apex and 104 on
// the landing, hands solved as an offset from their own shoulder.
//
// JUMP and SIT, solved the same way and for the same reason: the women's
// pack ships no Sitting and no Jump clip (see research/qlifegen/glbavatar.py),
// so both are hand poses on the bones — which is what swimPose and the skate
// stance already were. TUCK is the apex, REACH is the extended leg at launch
// and landing, SIT is the vespa. Same knob order as SKATE_KNOBS.
const JUMP_TUCK = [-0.3936, -0.9346, 0.373, 1.2762, -0.5861, -0.0025, 1.2578,
  0.3937, -0.812, -0.007, 0.0143, 0.8, 0.1612, -0.45, -0.9176, -1.3259,
  -1.125, -0.086, 0.4255, 0.9142, -0.5436, 1.0407];
const JUMP_REACH = [-0.5258, -0.0815, 0.1386, -0.0457, 0.1428, 0.0279,
  0.0109, 0.3734, 0.1068, 0.0492, 0.1549, -0.0133, -0.113, 0.4453, -0.6914,
  -0.6767, -0.3586, -0.0766, -0.4604, 0.9117, -0.2084, 0.2462];
const SIT_POSE = [-0.45, -1.3736, 0.5835, 1.431, -1.1202, -0.1562, 1.487,
  0.45, -0.1125, -0.0773, 0.0101, 0.2014, -0.3883, -0.45, -0.675, -0.3204,
  -1.0137, 0.938, 0.5625, 0.2391, -0.3722, 0.5902];

// RE-SOLVED 2026-08-27 ONTO THE DECK SHE IS ACTUALLY STANDING ON. The table
// this replaces was solved against a deck height that had never been measured
// against the board mesh, so the whole figure rode 55mm ABOVE her own board in
// every state that is not a push — visible from any angle, and the owner's
// "the body all contorted". data/stancecheck.mjs measures the sole against the
// grip-tape mesh itself and is the gate that would have caught it.
//
// AND THE CHEST IS OPEN NOW. The old table put the shoulder line 16.7 deg off
// the deck — nearly a photo-pose 90 deg of chest — which forced 79 deg of NECK
// to look down the road. That is the "cannot tell which side she is facing":
// the body reads sideways and the head reads forward at the same time. The
// shoulder line opens to 35 deg, chest about -55, neck about 60. Nothing below
// the waist moved. See data/rigsolve/stance.mjs `shoulderAxis`.
// RE-SOLVED AGAIN 2026-08-27 (evening) — THE FIGURE TILTS NOW. The owner, on
// the build above: "the body pls more naturual dont like forced to face
// straight ... surfskating is like surfing their position tilted one direction
// more and standing like surfing." He is right and the frame proves it:
// shots/ridecam/base0.cruise.front.jpg is a woman standing dead square to the
// camera, shoulders level, both arms straight down. Four targets changed in
// data/rigsolve/stance.mjs, each with its own note there:
//   * the HEAD sits over the front foot and out toward the toe rail, so the
//     spine inclines about 9 deg across and 17 along instead of standing plumb
//   * the SHOULDER LINE is no longer horizontal — the leading shoulder drops
//   * the ARMS come up to waist level and out over the rails (surfskate.love:
//     "hold your arms up parallel to the ground"), asymmetric, elbows soft
//   * she LOOKS DOWN THE LINE, canted to the toe side with her chest, which
//     also takes the neck from 61 deg to about 44
const SKATE_STAND = [-0.4625, -0.332, 0.2965, 0.1355, 0.5793, -0.0047, -0.0609,
  -0.6051, -0.1074, 0.048, 0.9719, 0.0664, -0.1461, -0.0508, -0.1125, 0.0934,
  0.0488, -0.2461, -0.1176, 1.0047, -0.1059, -0.5789];
const SKATE_DELTA = [0.201, -0.6645, 0.3334, 0.9656, -0.4093, -0.1564, 1.0512,
  0.1014, 0.0797, -0.1813, -0.2798, 0.0012, 0.8071, 0.1605, -0.3483, 0.5066,
  -0.5016, 0.6, 0.0589, 0.1953, 0.2265, 0.8443];
// How far the pelvis rides below its rest height, in METRES, cruising and at
// full carve. IMPOSED, not solved — see the note in skatePose.
// ...and the pelvis came down the same 55mm with them. Dropping the feet
// alone straightened the knees to 142/149 deg — a rider standing to attention
// on a moving board — because feet and hips are one coupling, which is the
// same fact the note in skatePose() records from the other end. Knees read
// 122/129 deg cruising and 100/106 in the carve, as before.
// HOW FAR ACROSS THE DECK EACH SHOE POINTS, in degrees from the nose. 90 is
// square across the plank. Front foot slightly open toward the nose, back foot
// all but square on the tail — the surfskate pair. See aimFoot().
const FOOT_YAW = [62, 88];
const SKATE_HIP = [0.035, 0.270];
// THE PUSH, solved onto the road for this rig: the six leg angles in the
// order [UpperLeg.L X, UpperLeg.L Z, LowerLeg.L X, UpperLeg.R X,
// UpperLeg.R Z, LowerLeg.R X] plus the pelvis drop in METRES. PLANT is the
// shoe down beside the board, DRIVE is the sweep behind it.
// RE-SOLVED 2026-08-27 against a MEASURED deck and a MEASURED road. The pair
// this replaces aimed the pushing shoe at a road 62mm below the real one (the
// solver held deck +0.037 / road -0.160, 197mm apart; measured, the deck sits
// 135mm over the road and is at -0.018). PLANT now reaches the road exactly —
// solver cost 0.0000 — so the shoe PLANTS instead of skimming. See the note at
// the foot of data/rigsolve/push.mjs.
// HOW FAR THE CHEST UNWINDS INTO A PUSH, in radians. The cruising chest sits
// about -55 deg across the deck; 0.72 rad brings it to roughly -14 deg, which
// is "forward facing" without snapping her square to the nose like a scooter
// rider. Measured by data/stancecheck.mjs as `chest` in the push row.
// CUT WITH THE MOVE TO A HEEL-SIDE PUSH, and the two are one decision. 0.72
// rad took the chest from about -55 deg across the deck to -14, all but square
// to the nose, on nollieskateboarding's "your body and your line of sight
// should be forward facing as you push". That is right for a TOE-side push,
// where the leg goes down on the side the rider has just turned to face. The
// owner's call is the heel side (2026-08-27: "heel pushing foot"), which is
// the side her BACK faces — so unwinding her toward the nose first turns a
// reach behind into a reach across the body. 0.24 keeps a hint of the turn
// without fighting the leg. See the note at the foot of data/rigsolve/push.mjs.
const PUSH_OPEN = 0.24;
const PUSH_PLANT = [-0.8051, 0.4315, 0.8692, 0.3696, -0.2711, 0.0505, 0.190];
// DRIVE HOLDS THE PLANT'S DEPTH (0.255, not 0.230). She was rising 25mm while
// still driving the foot back, which left the sole 22mm over the road at full
// stretch — measured, not guessed. See the note in data/rigsolve/push.mjs.
const PUSH_DRIVE = [-0.8053, 0.4315, 0.8696, 0.8036, -0.1232, -0.1893, 0.190];

export function buildAvatar(hat) {
  // ---- bones: the armature subtree verbatim, so clips need no retarget
  const bones = AVATAR.bones.map((b) => {
    const bn = new THREE.Bone();
    bn.name = b.n;
    bn.position.fromArray(b.t);
    bn.quaternion.fromArray(b.r);
    return bn;
  });
  const roots = [];
  AVATAR.bones.forEach((b, i) => {
    if (b.p >= 0) bones[b.p].add(bones[i]);
    else roots.push(bones[i]);
  });
  const byName = {};
  bones.forEach((bn) => { byName[bn.name] = bn; });

  // ---- geometry: merged primitives, wardrobe-group vertex colors
  const M = AVATAR.mesh;
  const nv = M.p.length / 3;
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(M.p, 3));
  g.setAttribute('normal', new THREE.Float32BufferAttribute(M.n, 3));
  const groupLin = AVATAR.groups.map((k) => lin(WARDROBE[k]));
  const cols = new Float32Array(nv * 3);
  for (let i = 0; i < nv; i++) {
    const c = groupLin[M.g[i]];
    cols[i * 3] = c[0]; cols[i * 3 + 1] = c[1]; cols[i * 3 + 2] = c[2];
  }
  g.setAttribute('color', new THREE.BufferAttribute(cols, 3));
  g.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(M.j, 4));
  g.setAttribute('skinWeight', new THREE.Float32BufferAttribute(M.w, 4));
  g.setIndex(M.i);

  const mesh = new THREE.SkinnedMesh(g,
    new THREE.MeshLambertMaterial({ vertexColors: true }));
  mesh.castShadow = true;
  // glTF skinning IGNORES the skinned mesh node's own transform: world =
  // sum(w * jointWorld * IBM) * vertex. So the Blender pre-transform
  // (-90degX, x100) goes on the bones' ANCESTOR group, the mesh stays at
  // identity, and the bind matrix is identity. Putting the pre-transform
  // on the mesh instead rendered a 180m giant (vet 2026-08-22).
  const arm = new THREE.Group();
  arm.quaternion.fromArray(AVATAR.pre.r);
  arm.scale.setScalar(AVATAR.pre.s);
  roots.forEach((r) => arm.add(r));

  const inverses = [];
  for (let j = 0; j < AVATAR.joints.length; j++) {
    inverses.push(new THREE.Matrix4().fromArray(
      AVATAR.ibm.slice(j * 16, j * 16 + 16)));
  }
  const root = new THREE.Group();
  // the pack character is authored 4.84 units tall (measured in
  // glbavatar.py's source GLB); the player is 1.72m like the old figures —
  // one uniform scale on the root, poses and clips untouched
  // 1.60 not 1.72: the old skater CROUCHES to ~1.45m head height and the
  // first trial read a full head too tall beside the 0.85m board (owner:
  // "too big", then still tall at 1.60) — 1.55 standing + the stance
  // crouch matches the old rider's presence.
  // WIDER than authored: the pack figure is lanky with a small head and
  // the owner read it as "weird alien" — 14% broader in x/z plus a
  // bigger head (below) puts him back at the old rider's chunky presence.
  // 4.841 WAS A MEASUREMENT OF ONE MODEL, TYPED IN. The woman is authored
  // 1.85 units tall, so the man's literal made her a 4-metre giant on the
  // first boot. glbavatar.py measures the source mesh now and ships `h`.
  const K = 1.55 / AVATAR.h;
  root.scale.set(K * 1.14, K, K * 1.14);
  byName.Head.scale.setScalar(1.16);
  // and the twig ARMS fill out a touch: bones run +Y so x/z is thickness.
  // 1.18 with the palms counter-scaled — the scale rides down the chain
  // and unchecked it ballooned the hands into mitts; legs were tried at
  // 1.18 too and REVERTED (the skinned shorts balloon into capris).
  // the wrist bone is 'Palm' on one pack and 'Wrist' on the other; the bake
  // reports which, rather than this file guessing from a name it knows
  for (const s of ['L', 'R']) {
    byName['UpperArm.' + s].scale.set(1.18, 1, 1.18);
    const w = byName[AVATAR.hand + '.' + s];
    if (w) w.scale.set(1 / 1.18, 1, 1 / 1.18);
  }
  root.add(arm);
  root.add(mesh);

  // HEADGEAR keeps the wardrobe's one rule that may differ per figure:
  // cap on foot and on the board, helmet on the scooter (wardrobe.js).
  // Parented to the Head bone; the bone's accumulated scale is
  // 100 * (1.72/h) = 35.53 on the man, 92.97 on the woman, so headgear
  // authored in metres divides it back out. `h` is the model's authored
  // height, measured by the bake — see the note at K above.
  if (hat) {
    const hg = new THREE.Group();
    const inv = 1 / (AVATAR.pre.s * (1.72 / AVATAR.h));
    hg.scale.setScalar(inv);
    const col = hat === 'helmet' ? WARDROBE.helmet : WARDROBE.cap;
    const hmat = new THREE.MeshStandardMaterial({ color: col,
      roughness: hat === 'helmet' ? 0.3 : 0.6 });
    const dome = new THREE.Mesh(new THREE.SphereGeometry(
      hat === 'helmet' ? 0.125 : 0.115, 14, 10, 0, Math.PI * 2, 0,
      Math.PI * 0.55), hmat);
    dome.castShadow = true;
    hg.add(dome);
    if (hat === 'cap') {
      // THINNER AND CLOSER IN. At 0.02 thick and 0.09 long standing 0.12 out
      // from the head's centre, the peak cleared her face by 30mm and caught
      // the sun as a flat white slab across it whenever the head turned —
      // visible in every carve frame. A real cap peak is a thin curve that
      // sits ON the brow.
      const peak = new THREE.Mesh(new THREE.BoxGeometry(0.15, 0.012, 0.075), hmat);
      peak.position.set(0, -0.022, 0.105);
      // ANGLED DOWN OVER THE BROW. Flat, it stood out horizontally and cut a
      // white bar across her eye in every frame where the head was turned at
      // all — the crown is white and the peak caught the sun the same way, so
      // it read as a slab through her face rather than as a cap.
      peak.rotation.x = 0.30;
      peak.castShadow = true;
      hg.add(peak);
    }
    byName.Head.add(hg);
    // ON THE CROWN, MEASURED. This was `set(0, 0.0029, 0.0002)` — Head-BONE
    // local units, hand-tuned against one model — and bone units are not
    // metres and are not the same between packs. Head_end IS the top of the
    // skull in exactly those units, so the crown is a fraction along it.
    const skull = byName.Head_end ? byName.Head_end.position.y : 0.0029;
    hg.position.set(0, skull * 0.86, skull * 0.07);
    hg.rotation.x = 0.1;
  }
  root.updateMatrixWorld(true);
  mesh.bind(new THREE.Skeleton(AVATAR.joints.map((j) => bones[j]), inverses),
    new THREE.Matrix4());

  // ---- deterministic clip sampler (no AnimationMixer: sampling is a
  // pure function of (clip, t), which is the property the goldens need)
  const rest = AVATAR.bones.map((b) => ({ t: b.t, r: b.r }));
  const resetPose = () => {
    bones.forEach((bn, i) => {
      bn.position.fromArray(rest[i].t);
      bn.quaternion.fromArray(rest[i].r);
    });
  };
  const _qa = new THREE.Quaternion(), _qb = new THREE.Quaternion();
  const sample = (name, t) => {
    const clip = AVATAR.clips[name];
    const tt = ((t % clip.dur) + clip.dur) % clip.dur;
    for (const tr of clip.tracks) {
      const times = tr.t;
      let k = 0;
      while (k < times.length - 1 && times[k + 1] < tt) k++;
      const k1 = Math.min(k + 1, times.length - 1);
      const span = times[k1] - times[k];
      const f = span > 0 ? (tt - times[k]) / span : 0;
      const bn = bones[tr.b];
      if (tr.p === 'rotation') {
        _qa.fromArray(tr.v, k * 4);
        _qb.fromArray(tr.v, k1 * 4);
        bn.quaternion.copy(_qa).slerp(_qb, f);
      } else if (tr.p === 'translation') {
        bn.position.set(
          tr.v[k * 3] + (tr.v[k1 * 3] - tr.v[k * 3]) * f,
          tr.v[k * 3 + 1] + (tr.v[k1 * 3 + 1] - tr.v[k * 3 + 1]) * f,
          tr.v[k * 3 + 2] + (tr.v[k1 * 3 + 2] - tr.v[k * 3 + 2]) * f);
      }
    }
  };

  const rot = (name, x, y = 0, z = 0) => {
    const bn = byName[name];
    if (bn) bn.rotation.set(bn.rotation.x + x, bn.rotation.y + y,
      bn.rotation.z + z);
  };
  // ADDING TO AN EULER ONLY WORKS FROM THE REST POSE, AND THAT IS A TRAP.
  //
  // `rot` above adds to bone.rotation, which three.js derives from the
  // quaternion in XYZ order. From the rest pose that is fine and it is what
  // swimPose and skatePose have always done. Applied ON TOP OF A SAMPLED
  // CLIP it silently does the wrong thing: the jump clip leaves UpperArm at
  // a quaternion whose XYZ decomposition is nothing like a single X angle,
  // so `rot('UpperArm.L', -1.3)` moved the arm barely at all while the same
  // call on LowerArm (near-zero y/z) worked — which is exactly what the vet
  // frame showed, forearms folding and the shoulders still overhead.
  //
  // Post-multiplying a quaternion turns the correction in the bone's OWN
  // frame after whatever the clip said, which is what "bend this joint
  // further" actually means, and it is correct from any starting pose.
  const _qd = new THREE.Quaternion(), _ax = new THREE.Vector3();
  const qrot = (name, ax, ay, az, angle) => {
    const bn = byName[name];
    if (!bn || !angle) return;
    bn.quaternion.multiply(_qd.setFromAxisAngle(_ax.set(ax, ay, az), angle));
  };
  // the rig is a Blender IK export: Foot.L/R are SIBLINGS of the leg
  // chain, parented to the root bone. Clips animate them directly; any
  // hand pose must move them too or the feet stay nailed to the floor
  // while the legs swing (the first swim vet's "bowing on all fours").
  const mov = (name, x, y = 0, z = 0) => {
    const bn = byName[name];
    if (bn) bn.position.set(bn.position.x + x, bn.position.y + y,
      bn.position.z + z);
  };

  // METRES PER BONE-UNIT of a Body translation, MEASURED on this rig rather
  // than derived from pre.s and the root scale by hand. The two packs differ
  // by a factor of 2.6 here (the woman is authored 1.85 units tall against
  // the man's 4.84), so a pelvis drop written in bone units is a different
  // distance on each figure — which is the whole class of bug `AVATAR.h`
  // exists to close.
  const BODY_UNIT = (() => {
    const v = new THREE.Vector3();
    root.updateMatrixWorld(true);
    byName.Hips.getWorldPosition(v);
    const y0 = v.y;
    byName.Body.position.y += 0.001;
    root.updateMatrixWorld(true);
    byName.Hips.getWorldPosition(v);
    byName.Body.position.y -= 0.001;
    root.updateMatrixWorld(true);
    return (v.y - y0) / 0.001;
  })();

  // SNAP THE FEET TO THE SHINS. The rig has no runtime IK: rotating the
  // leg chains moves the shins but the root-parented Foot bones stay put,
  // so the shoes detach from the legs (the owner's "not stepping properly
  // on the board"). After any hand-posed legs, put each Foot bone exactly
  // at its shin's end. Bones extend along local +Y; shin length measured
  // from the rest pose at build time.
  const _w = new THREE.Vector3(), _w2 = new THREE.Vector3();
  const _q = new THREE.Quaternion();
  const shinLen = {};
  for (const s of ['L', 'R']) {
    byName['LowerLeg.' + s].getWorldPosition(_w);
    byName['Foot.' + s].getWorldPosition(_w2);
    shinLen[s] = _w.distanceTo(_w2);
  }
  // ...AND THE SHIN ENDS WHERE THE RIG SAYS IT ENDS, NOT ALONG +Y.
  //
  // This used to place the foot at `LowerLeg + Yhat * shinLen`, on the comment
  // above ("bones extend along local +Y"). MEASURED on this rig, in the shin's
  // own frame, live: the tip bone `LowerLeg.R_end` sits at (-0.0095, 0.4676,
  // 0.0292) and the +Y assumption puts the ankle at (0, 0.4508, 0). That is
  // 35mm apart in the shin's frame, and 3.6 degrees off its axis -- and the
  // shin swings through most of a right angle between standing and a deep
  // carve, so in the BOARD's frame the error rotates into a fore/aft slide
  // along the deck.
  //
  // What it cost: data/rigsolve/stance.mjs aims the foot targets at
  // `LowerLeg.X_end`, and the runtime planted the shoe somewhere else, so the
  // solve could hit its target exactly and still stand her in the wrong place.
  // Measured at the carve: the shin end 79-87mm off its truck (the solver's
  // 90mm, near enough) while the SHOE was 133-152mm off it, against
  // stancecheck's 140mm budget. The gate has been reporting a pose defect that
  // is really this arithmetic.
  //
  // The tip bone is a real bone in the hierarchy, so it needs no measured
  // constant and no assumption about which way a bone points: read its world
  // position and put the ankle there. `shinLen` stays for rigs that have no
  // tip bone.
  const shinEnd = { L: byName['LowerLeg.L_end'] || null, R: byName['LowerLeg.R_end'] || null };
  const snapFeet = () => {
    root.updateMatrixWorld(true);
    for (const s of ['L', 'R']) {
      const low = byName['LowerLeg.' + s];
      const foot = byName['Foot.' + s];
      if (shinEnd[s]) {
        shinEnd[s].getWorldPosition(_w);
      } else {
        low.getWorldPosition(_w);
        low.getWorldQuaternion(_q);
        _w2.set(0, 1, 0).applyQuaternion(_q).multiplyScalar(shinLen[s]);
        _w.add(_w2);
      }
      foot.parent.worldToLocal(_w);
      foot.position.copy(_w);
    }
  };

  // POINT A SHOE A GIVEN NUMBER OF DEGREES ACROSS THE DECK — absolutely, not
  // as a nudge off the rest pose. `yaw` is measured from the board's NOSE
  // (+z in the rig's frame): 0 would lay the shoe along the plank, 90 puts it
  // square across, and the toes always point to the TOE side (-x).
  //
  // The shoe's own long axis is NOT assumed to be the bone's +y: it is read
  // from where the toe bone actually sits, so a different character with a
  // different rest foot cannot silently rotate every shoe by whatever the
  // difference happens to be. skatePose zeroes root.rotation.y and the root
  // hangs off the board with only a height offset, so the root's axes ARE the
  // board's axes and a yaw stated here is a yaw you could protractor off an
  // overhead frame.
  const _toeAxis = {};
  for (const s of ['L', 'R']) {
    const toe = byName['Foot.' + s + '_end'] || byName['Toe.' + s];
    _toeAxis[s] = toe ? toe.position.clone().normalize() : new THREE.Vector3(0, 1, 0);
  }
  // own scratch quaternions — `_qa`/`_qb` are already taken by sample()
  const _fq = new THREE.Quaternion(), _fq2 = new THREE.Quaternion();
  const _d = new THREE.Vector3(), _dw = new THREE.Vector3();
  const aimFoot = (name, yawDeg) => {
    const b = byName[name];
    if (!b) return;
    const side = name.endsWith('.L') ? 'L' : 'R';
    root.updateMatrixWorld(true);
    const a = yawDeg * Math.PI / 180;
    // where the toes should point, in the ROOT (= board) frame, then in world
    _d.set(-Math.sin(a), 0, Math.cos(a));
    _dw.copy(_d).applyQuaternion(root.getWorldQuaternion(_fq));
    // where they point NOW
    b.getWorldQuaternion(_fq2);
    const cur = _toeAxis[side].clone().applyQuaternion(_fq2).normalize();
    // the minimal world rotation from one to the other keeps the sole as flat
    // as the rest pose had it, which is what a foot on a deck wants
    const fix = new THREE.Quaternion().setFromUnitVectors(cur, _dw.normalize());
    const want = fix.multiply(_fq2);
    b.parent.getWorldQuaternion(_fq);
    b.quaternion.copy(_fq.invert().multiply(want));
  };

  return {
    group: root,
    bones: byName,
    sample,
    resetPose,
    // walking / running — the embedded clips, phase-driven like the old
    // figure (phase advances by speed*dt*2.4 in main.js; one walk cycle
    // was 2*PI of phase there, one clip is clip.dur seconds here)
    pose(phase, speed) {
      resetPose();
      if (speed <= 0.1) { sample('idle', phase * 0.35); return; }
      const run = speed > 2.6;
      const clip = run ? 'run' : 'walk';
      sample(clip, (phase / (Math.PI * 2)) * AVATAR.clips[clip].dur);
    },
    // breaststroke — no swim clip exists in the pack; the owner picked
    // breaststroke on the OLD figure (2026-08-14) and this ports that
    // exact cycle onto the bones: arms reach-sweep together, frog kick
    // half a cycle behind, head up, prone pitch handled by main.js on the
    // group as before.
    swimPose(phase) {
      resetPose();
      // prone pitch on the ROOT bone (parents the whole figure including
      // the IK feet); the old walker pitched its body group the same way
      rot(AVATAR.root, 1.45);
      const t = phase * 1.35;
      const s = Math.sin(t);
      const pull = Math.max(0, s);
      const draw = Math.max(0, Math.sin(t - Math.PI * 0.15));
      const reach = -2.35 + pull * 1.45;
      rot('UpperArm.L', reach, 0, 0.28 + pull * 0.5);
      rot('UpperArm.R', reach, 0, -0.28 - pull * 0.5);
      rot('LowerArm.L', 0.15 + pull * 0.7);
      rot('LowerArm.R', 0.15 + pull * 0.7);
      // legs stay LOW amplitude: the IK feet are root-parented, so big leg
      // swings would leave them behind; the kick is underwater anyway and
      // the breaststroke read lives in the arm sweep + head
      rot('UpperLeg.L', -draw * 0.3);
      rot('UpperLeg.R', -draw * 0.3);
      rot('LowerLeg.L', draw * 0.55);
      rot('LowerLeg.R', draw * 0.55);
      rot('Head', -1.0);
      snapFeet();
    },
    // JUMPING — on foot, and the GAME owns the height.
    //
    // The men's pack had a jump clip and this used to play it with the arms
    // corrected on top, because the clip's own arms threw overhead and HELD
    // there: an animator's celebratory leap, which read as a stiff Y-pose
    // floating across the beach walk. The women's pack has no jump clip at
    // all, so the pose is solved outright — and solving it is the better
    // answer anyway, since the thing being corrected was most of the clip.
    //
    // TWO SOLVED POSES AND A BELL BETWEEN THEM. REACH is the extended leg,
    // which is both the launch and the landing; TUCK is the apex, knees at
    // 60 deg with the arms up and bent at 100 deg. `u` is the airborne
    // progress the physics reports: 0 at launch, ~0.5 at apex, 1 at
    // touchdown, past 1 for the settle. sin(pi*u) is 0 at both ends and 1 at
    // the apex, which is exactly the shape of a hop.
    //
    // The crouch of anticipation is deliberately NOT played — a hop that
    // waits 0.2s before it leaves the ground feels like lag, and the owner
    // asked for a hop you can chain.
    jumpPose(u) {
      resetPose();
      const air = Math.max(0, Math.min(1, u));
      const settle = Math.min(0.5, Math.max(0, u - 1));
      const tuck = Math.sin(Math.PI * air);
      // past touchdown the whole pose eases back toward rest rather than
      // holding a landing crouch the physics has already finished with
      const w = 1 - settle * 2;
      for (let i = 0; i < SKATE_KNOBS.length; i++) {
        const k = SKATE_KNOBS[i];
        const a = (JUMP_REACH[i] + (JUMP_TUCK[i] - JUMP_REACH[i]) * tuck) * w;
        if (!a) continue;
        qrot(k[0], k[1], k[2], k[3], a);
      }
      // the Foot bones are root-parented siblings of the leg chain, so a
      // hand-posed leg leaves them behind (see snapFeet). The clip used to
      // animate them directly; nothing does now.
      snapFeet();
    },
    // seated on the vespa — solved, for the same reason as the jump: no
    // Sitting clip in this pack. Thighs forward, knees at 96 deg, hands out
    // to the bars with the elbows soft. main.js still pulls knees and arms
    // the last few centimetres onto the bars and the floorboard.
    sitPose() {
      resetPose();
      for (let i = 0; i < SKATE_KNOBS.length; i++) {
        const k = SKATE_KNOBS[i];
        if (!SIT_POSE[i]) continue;
        qrot(k[0], k[1], k[2], k[3], SIT_POSE[i]);
      }
      snapFeet();
    },
    // ================= THE SKATE STANCE =================
    //
    // REBUILT 2026-08-26 on the owner's report: "the avatar position fucking
    // unnatural and weird ... I want the best suited avatar and best you can
    // do for it when skating or whatever or moving." He was right, and the
    // vet sheet said exactly what he was seeing: BOTH ARMS STRAIGHT OUT
    // SIDEWAYS at shoulder height, elbows locked, torso upright, knees
    // barely bent. A scarecrow on a board.
    //
    // WHY THE PREVIOUS SOLVE PRODUCED THAT. It optimised the HAND POSITIONS
    // and put only a light penalty on the elbow, on a rig whose arms are
    // short: the cheapest way to reach a target 0.35m from a 0.37m shoulder
    // is to point the whole arm at it. Numbers right, frame wrong — which
    // the note it replaced had itself warned about.
    //
    // AND THEN REJECTED AGAIN, because the second version was invented too:
    // "the arms still like forward and backward in such fucking weird
    // positions and unnatural. You need go online see or not how it should be
    // like." He was right twice. I had reasoned out a "surf carry" — leading
    // arm forward over the nose, trailing arm back past the hip — from
    // nothing, and solved hard for it.
    //
    // WHAT THE PEOPLE WHO TEACH IT ACTUALLY SAY (Sikana's skater stance,
    // and the beginner guides at retrospec / thesupplynetwork):
    //   * "your arms usually stay by your sides", hanging naturally, and
    //     extend only SLIGHTLY for balance. Shoulders relaxed.
    //   * "shoulders in line with your feet" — the shoulder line runs ALONG
    //     the deck and the chest faces the toe side.
    //   * knees bent and loose at all times; back straight; look ahead.
    //   * feet a little wider than shoulder width, evenly placed between the
    //     trucks, front foot ~45 deg, back foot near perpendicular.
    // So the hands now hang about 0.94 of full arm reach BELOW their own
    // shoulder, a few centimetres off the hip, and open out only into the
    // carve. Nothing reaches for anything.
    //
    // TWO MEASUREMENT BUGS WERE HIDING INSIDE "MAKE THE ARMS HANG", and both
    // made the solver produce a folded arm while hitting its target exactly:
    //   * the hand targets were absolute points fixed to the REST shoulder.
    //     Once the chest turns, a point in space is no longer beside the body
    //     it belongs to. They are offsets from the LIVE shoulder now.
    //   * "arm length" was the rest-pose shoulder-to-wrist distance, 0.377 —
    //     but this rig rests in an A-pose with the elbow ALREADY BENT, so
    //     that is not full reach. Full reach is the two segments added:
    //     0.393. A hang set to 0.94 of the short number still needs a
    //     132-degree elbow. Elbows read 150/145 deg cruising now.
    //
    // WHAT IS DIFFERENT NOW:
    //   * the elbow and KNEE angles are first-class objectives, not
    //     tie-breakers, and the hand targets were pulled INSIDE reach
    //     (0.285/0.300 against a 0.37m arm) so the elbow has to fold;
    //   * the crouch is a real crouch — the pelvis is a target, dropping
    //     0.105m with the feet pinned, so the knees go 139 deg -> 120 deg
    //     instead of both solves landing on the same near-straight leg;
    //   * the two solves are REGULARISED toward each other. The pose ships
    //     as a lerp between them and two independent solves landed in
    //     different basins (Torso twist +1.31 against -0.23), so the lerp
    //     swung the chest through the body on its way across;
    //   * the head is solved to LOOK DOWN THE ROAD rather than given a
    //     hand-picked counter-rotation.
    //
    // AND IT IS A TABLE, NOT TWENTY qrot LINES. The solver emits a vector in
    // this knob order; pasting it back as prose is how the last version's
    // numbers and its comments drifted apart. scratchpad/stance.mjs +
    // rig.mjs + solve.mjs regenerate STAND/DELTA — re-solve, do not nudge.
    //
    // Regular footed: LEFT foot forward, feet 0.48m apart along the deck and
    // all but on its centreline, hips slightly open, shoulders open more,
    // leading arm forward over the nose-side rail at chest height, trailing
    // arm back and low by the hip.
    skatePose(lean = 0, crouch = 0, kick = 0, reach = 0, ride = 0, slip = 0) {
      resetPose();
      root.rotation.y = 0;
      const c = Math.max(0, Math.min(1, crouch));
      // THE ARMS OPEN WITH THE TURN, THE LEGS FOLD WITH THE WORK. One blend
      // scalar drove both and it was the wrong one for the arms: `crouch` is
      // mostly SPEED (main.js: v*0.5 + |carve|*0.5), so coasting through a
      // full-lock turn it sits near 0.5 and the arms only ever got half way
      // out — which is why the trailing hand still hung by the deck in
      // shots/ridecam/t8.carve-hard.heel.jpg after the runtime swing was
      // removed. A rider throws their arms out because they are TURNING, not
      // because they are going fast. `lean` is the signed carve; its
      // magnitude is what the arms answer to.
      const armOpen = Math.min(1, Math.abs(lean) / 0.30);
      for (let i = 0; i < SKATE_KNOBS.length; i++) {
        const k = SKATE_KNOBS[i];
        const w = /Arm/.test(k[0]) ? Math.max(c, armOpen) : c;
        const a = SKATE_STAND[i] + w * SKATE_DELTA[i];
        qrot(k[0], k[1], k[2], k[3], a);
      }
      // THE PELVIS RIDES LOW, AND IT IS IMPOSED RATHER THAN SOLVED. As a
      // twenty-third knob it never moved: coordinate descent changes one
      // thing at a time, and lowering the hips ON THEIR OWN always scores
      // worse because the feet come down with them — the knees have to fold
      // in the same step for it to pay. Three solves running reported the
      // pelvis at its REST height through a full carve, with the knees at
      // 148 degrees because a 0.57m stance at that height is already at full
      // leg extension. Set the height, and the legs answer for it: knees now
      // read 122 deg cruising and 100 deg in the carve.
      mov('Body', 0, -(SKATE_HIP[0] + c * (SKATE_HIP[1] - SKATE_HIP[0])) / BODY_UNIT, 0);
      // the carve, on top of the solved stance: the chest rolls into the
      // turn and the arms swing across as a counterweight. Unchanged in
      // spirit from the pose this replaces — it was never the complaint.
      // DEEPER 2026-08-27. `lean` arrives as carve*0.35, so 0.55 capped the
      // roll at 11 degrees at full lock — a lean you have to look for. The
      // owner's whole note is that the figure does not tilt ("their position
      // tilted one direction more"), and a surfskate turn IS the rider's
      // incline: the board cannot lean far, the person does. 0.95 puts full
      // lock at 19 deg on top of the stance's own resting tilt, and the arms
      // counter across the deck a little harder with it.
      // THE RIDER COUNTERS THE BOARD, SHE DOES NOT ADD TO IT.
      //
      // main.js:6205 rolls the WHOLE skate rig by S.lean, and SKATE.leanMax is
      // 0.80 rad — the board goes over 46 degrees at full lock, deliberately
      // ("it goes right over"). The avatar rides inside that rig, so she is
      // already leaning 46 degrees before this line runs. Rolling her a further
      // 0.45 of the carve in the SAME direction stacked her to about 55, and
      // from behind she read as falling off the side rather than carving.
      //
      // A board tilts further than the rider standing on it: the deck rolls
      // under them while the upper body stays nearer the turn's centre. So
      // this counters, and she comes out around 37 degrees to the board's 46.
      qrot('Torso', 0, 0, 1, -lean * 0.45);
      // THE ARMS ARE THE STANCE'S JOB NOW, NOT A RUNTIME NUDGE.
      //
      // This block used to swing the back arm across on top of the solved
      // pose: a yaw, a roll and a forearm roll, all scaled by lean. It was
      // written when the stance held ONE arm shape for every state, so the
      // carve had to be faked here. It is not needed any more — the solve has
      // two real shapes now, arms hanging at cruise and thrown wide at full
      // carve, taken off photographs — and worse, it FOUGHT them: at full lock
      // the extra yaw dragged the trailing hand back down beside the deck,
      // which is the limb the owner read as a lunging leg
      // (shots/ridecam/t7.carve-hard.heel.jpg).
      //
      // What is left is the small counter-roll of the leading arm, and the
      // head leading the turn — both things the stance cannot know, because
      // it only sees how HARD she is working, never which way.
      qrot('UpperArm.L', 0, 0, 1, -lean * 0.16);
      qrot('Torso', 0, 1, 0, lean * 0.22);
      qrot('Head', 0, 1, 0, lean * 0.26);

      // ---- the push, SOLVED onto the road (ride.js: "a push runs out") ----
      //
      // RE-SOLVED 2026-08-26 for this rig. The numbers here were solved
      // against the man's proportions and mean nothing on a different
      // skeleton — a table of joint angles is the most model-specific thing
      // in this file. Front foot pinned to its deck mark, back foot to the
      // road, both knees and the hip drop free; solved ON the cruising pose
      // it blends out of rather than on a rest figure.
      //
      //   PLANT  reaches the road EXACTLY (solver cost 0.0000)
      //   DRIVE  reaches it too, cost 0.0000, once she rides low enough
      //
      // THE "HONEST LIMIT" THAT USED TO BE RECORDED HERE WAS NOT A LIMIT. It
      // said a 1.55m figure could not reach the road and so the shoe had to
      // skim behind the tail. In fact the push was being solved against a road
      // 62mm below the real one, and once the road is measured the plant lands
      // on it with nothing left over. The real remaining limit is smaller and
      // With the deeper surfskate ride (SKATE_HIP 160/255mm) even the full
      // drive lands: there is no remaining reach limit. Worth keeping as a
      // lesson — a plausible note about proportions hid a wrong number for a
      // fortnight, and "the figure is too short" was never true.
      if (kick !== 0 || reach > 0) {
        // RECOVER THE STROKE PHASE. main.js hands over two derived numbers —
        // reach = 0.5 - 0.5cos(2*pi*p) and kick = sin(2*pi*p) — and blending
        // on them directly gets the timing wrong: the foot is most extended
        // when it is only half off the deck. Both come from one phase, and
        // cos/sin of it are recoverable exactly, so recover it and drive a
        // real cycle: down to the PLANT, sweep back to the DRIVE, return.
        const ph = Math.atan2(kick, 1 - 2 * reach) / (Math.PI * 2);
        const p01 = ph - Math.floor(ph);
        // A PUSH IS NOT SYMMETRIC, AND THIS ONE WAS (2026-08-28).
        //
        // `t = sin(PI * p01)` traces cruise -> PLANT -> DRIVE -> PLANT ->
        // cruise: the stroke plays forwards and then backwards through the
        // same two poses. Two things follow, and the handover has both of them
        // as complaints. The DRIVE — the whole point of the stroke — is
        // reached for one instant at p01 = 0.5 and left immediately, so
        // shooting five frames of a push returns three that look the same. And
        // the RECOVERY retraces the plant, which puts the foot back on the
        // road on the way home; a real recovery lifts it and swings it forward
        // clear of the ground.
        //
        // So the stroke is three named legs with their own durations, blending
        // between three poses rather than sliding along one path:
        //
        //     0.00-0.22   cruise -> PLANT   the foot comes down beside the deck
        //     0.22-0.62   PLANT  -> DRIVE   the stroke, and it is the long one
        //     0.62-1.00   DRIVE  -> cruise  straight home, NOT back via PLANT
        //
        // Proportions are the ordinary ones for a stride: a short reach out, a
        // long drive, and a recovery about as long as the drive because the
        // leg has further to travel and no ground to push against. No source
        // gives a skateboard push in percentages, so these are stated as
        // authored rather than measured.
        //
        // `t` survives as the COMMITMENT — how far she is from her cruising
        // stance, 0 on the deck and 1 fully extended — because the torso dip
        // and the chest unwind below are both continuous in it and always
        // were.
        const PL_END = 0.22, DR_END = 0.62;
        let legA, legB, legU;
        if (p01 < PL_END) { legA = 0; legB = 1; legU = p01 / PL_END; }
        else if (p01 < DR_END) { legA = 1; legB = 2; legU = (p01 - PL_END) / (DR_END - PL_END); }
        else { legA = 2; legB = 0; legU = (p01 - DR_END) / (1 - DR_END); }
        const ease = legU * legU * (3 - 2 * legU);
        const t = legA === 0 ? ease * 0.5
          : legA === 1 ? 0.5 + ease * 0.5
          : 1 - ease;
        // the stance angles this pose already applied, to blend away from —
        // READ FROM THE TABLE, not re-typed. They used to be six local
        // variables the stance block happened to leave lying around, which is
        // how a stance change silently stops matching the push it blends out
        // of. The seventh entry is the pelvis drop, in METRES here and
        // divided by BODY_UNIT at the point of use.
        const kv = (b, ax) => {
          const i = SKATE_KNOBS.findIndex((k) => k[0] === b
            && k[1] === ax[0] && k[2] === ax[1] && k[3] === ax[2]);
          return SKATE_STAND[i] + c * SKATE_DELTA[i];
        };
        const cur = [kv('UpperLeg.L', [1, 0, 0]), kv('UpperLeg.L', [0, 0, 1]),
                     kv('LowerLeg.L', [1, 0, 0]), kv('UpperLeg.R', [1, 0, 0]),
                     kv('UpperLeg.R', [0, 0, 1]), kv('LowerLeg.R', [1, 0, 0]),
                     SKATE_HIP[0] + c * (SKATE_HIP[1] - SKATE_HIP[0])];
        // the three poses the legs above name, as deltas from the stance
        const POSE = [cur, PUSH_PLANT, PUSH_DRIVE];
        const d = cur.map((cv, i) => {
          const from = POSE[legA][i] - cv, to = POSE[legB][i] - cv;
          return from + (to - from) * ease;
        });
        qrot('UpperLeg.L', 1, 0, 0, d[0]);
        qrot('UpperLeg.L', 0, 0, 1, d[1]);
        qrot('LowerLeg.L', 1, 0, 0, d[2]);
        qrot('UpperLeg.R', 1, 0, 0, d[3]);
        qrot('UpperLeg.R', 0, 0, 1, d[4]);
        qrot('LowerLeg.R', 1, 0, 0, d[5]);
        mov('Body', 0, -d[6] / BODY_UNIT, 0);
        qrot('Torso', 1, 0, 0, t * 0.14);         // body dips over the plant
        // AND SHE TURNS TO FACE WHERE SHE IS GOING WHILE SHE PUSHES.
        // nollieskateboarding's push tutorial: "Your body and your line of
        // sight should be forward facing as you push." That is the opposite of
        // the cruising stance, where the chest sits across the deck — and it
        // is right, because a push is a stride and you cannot stride sideways.
        // The shipped pose held the full cruising twist through the whole
        // stroke, so she kicked at the road with her chest pointing at the
        // kerb. Unwinds with the commitment `t` and winds back as the foot
        // returns to the deck.
        //
        // The head is a CHILD of the torso, so it takes this rotation too and
        // has to be given it back, or she turns to face forward and keeps on
        // turning until she is looking at the pavement beside her.
        qrot('Torso', 0, 1, 0, t * PUSH_OPEN);
        qrot('Head', 0, 1, 0, -t * PUSH_OPEN);
      }

      // ---- SHE IS ALIVE WHILE SHE ROLLS ----------------------------------
      //
      // The handover's standing complaint about this figure: "cruising at
      // 10 km/h and at 35 she is the identical frame. No pump, no weight
      // shift, no rise and fall, nothing breathing." The push is fixed above;
      // this is the other half, and it is the ride.
      //
      // `ride` is ONE signed number, already sine-shaped and already scaled by
      // speed in main.js. Everything below is a small multiple of it, so at a
      // standstill every term is EXACTLY ZERO and the resting figure is the
      // one that has always been photographed. That is not a nicety: the
      // handover records a resting change that "moved 27 of 40 goldens by
      // 0.10-0.16% — the rider is in every frame, so any resting change is an
      // island-wide diff for nothing".
      //
      // WHAT A SURFSKATER ACTUALLY DOES is PUMP: the board is driven by the
      // rider rising and sinking through the turn, not by pushing. So the
      // motion is a compression cycle — knees fold and extend, the pelvis
      // rides up and down with them, the chest follows a beat behind, and the
      // arms counterweight it. Amplitudes are deliberately small; this is
      // meant to read as a body working, not as a bounce.
      if (ride !== 0) {
        mov('Body', 0, (ride * 0.011) / BODY_UNIT, 0);
        qrot('LowerLeg.L', 1, 0, 0, -ride * 0.045);
        qrot('LowerLeg.R', 1, 0, 0, -ride * 0.045);
        qrot('UpperLeg.L', 1, 0, 0, ride * 0.026);
        qrot('UpperLeg.R', 1, 0, 0, ride * 0.026);
        // the chest lags the legs — a body absorbs from the ground up
        qrot('Torso', 1, 0, 0, ride * 0.020);
        qrot('Head', 1, 0, 0, -ride * 0.012);
        // ...and the arms hang off it, so they swing a little against it
        qrot('UpperArm.L', 1, 0, 0, -ride * 0.055);
        qrot('UpperArm.R', 1, 0, 0, -ride * 0.055);
      }

      // ---- SHE LOOKS WHERE SHE IS GOING, NOT WHERE THE BOARD POINTS -----
      //
      // The handover's third standing complaint about this figure: "she does
      // not look where she is going through a turn." MEASURED before writing
      // anything (scratchpad/looksweep.mjs, holding full throttle at six steer
      // values): the board slides up to 41 degrees across its own direction of
      // travel, and her head stays within 9 degrees of the NOSE the whole way.
      // So at full lock she is looking 41 degrees away from where she is
      // actually going -- across the slide, not down the road.
      //
      //     st     slip   head-vs-nose   head-vs-course
      //      0        0          -5.5            -5.5
      //   0.25   -0.639          -2.8           -39.4
      //      1   -0.706          -0.5           -40.9
      //     -1   +0.623          -8.9           +26.8
      //
      // THE SLIDE IS THE WHOLE POINT OF THE PICTURE and she was not in it. A
      // longboard or surfskate slide reads the way it does precisely because
      // the deck goes sideways while the rider's head and shoulders stay
      // pointed down the road -- it is the counter-rotation that says the
      // slide is intended. The old box rig knew this (its head took
      // `carve*0.42 + slip*0.34`); the rigged figure that replaced it was
      // never given the slip at all, so the term did not get worse, it
      // vanished.
      //
      // `course - heading` is exactly `-slip` (ride.js keeps both; verified
      // against the sweep above, both signs). So the gaze is carried back
      // toward the course by -slip, and it is SPLIT: the chest takes 0.42 of
      // it and the neck the rest. Two reasons, and the second is a budget:
      //   * a slide is a shoulder rotation, not a neck one. "Turn your head,
      //     then your shoulders" is what every skate guide says the turn is;
      //     shoulders pointing down the road is what the photographs show.
      //   * data/stancecheck.mjs budgets the neck at 75 degrees and it already
      //     reads 50 cruising -- the stance faces the toe side by design.
      //     Putting the whole 41 into the neck would ask her to look over her
      //     own shoulder past anything a neck can do.
      // AND THE TWO SUM TO 0.86, NOT 1.0, ON PURPOSE. Head is a child of
      // Torso, so the gaze moves by the sum. Landing exactly on the course
      // would be looking at where she is this instant; the exit of the turn is
      // a little further round than that, and in a drift "further round" is
      // toward the nose -- the deck is already pointing where the course is
      // heading next. Leaving 0.14 of the slip uncorrected is about 6 degrees
      // of lead into the turn at full lock, which is the "look through the
      // corner" every guide describes and no more.
      // Zero at a standstill, and zero in a straight line, so no golden frame
      // that is not a slide can move.
      if (slip !== 0) {
        qrot('Torso', 0, 1, 0, -slip * 0.42);
        qrot('Head', 0, 1, 0, -slip * 0.44);
      }

      // the IK feet are root-parented siblings of the leg chain, so they
      // must be bolted to the shin ends AFTER the legs move (see snapFeet)
      snapFeet();
      // ...and only THEN can they be AIMED across the deck.
      //
      // THIS USED TO BE `Foot.L.rotation.y += 0.62` / `Foot.R += 1.15` and it
      // is the owner's "the feet placement all facing weird". A `+=` on
      // rotation.y is a DELTA on the rest orientation, in the bone's own
      // parent frame — which has the rig's pre-rotation on it and no relation
      // to the board. So the two numbers were not "35 and 66 degrees across
      // the deck"; they were 35 and 66 degrees away from wherever the rest
      // foot happened to point, and shot from overhead both shoes lay ALONG
      // the plank, pointing at the nose. Nobody had ever looked from above.
      //
      // AND IT IS A SURFSKATE, WHICH IS ITS OWN DISCIPLINE. The guides for it
      // (surfskate.love's foot-position guide; the surf stance it copies) say
      // the feet ride essentially PERPENDICULAR to the deck: the front foot
      // just behind the front bolts with the toes on the rail and only a
      // slight angle toward the nose, the back foot square across the tail.
      // Traditional surfing states the same pair as 45 deg front / 90 deg back
      // to the stringer; a surfskate sits between, nearer the square end.
      //
      // Aimed ABSOLUTELY now, in the board's frame, so the number in the code
      // is the angle you would measure in a photograph.
      aimFoot('Foot.L', FOOT_YAW[0]);
      aimFoot('Foot.R', FOOT_YAW[1]);
    },
  };
}
